### ISSUE TITLE
How can I customise the filtering function?

### ISSUE THREAD

**Issue by k290** [i-like-robots/react-tags#141] opened 2018-11-13 09:03 UTC
Other tag libraries have allowed me to change the filtering using a prop such as handleFilterSuggestions.
This allows the tag input to provide suggestions using "contains" rather than "startsWith" as an example.

How do I do this with this library?

**Comment by i-like-robots** [comment] 2018-11-21 15:42
It is not currently an option nor planned to add an option for supporting a custom filtering function.

I marked #82 which suggested this feature as "wontfix" because there was no further interest in the feature. I don't plan to revisit that decision myself but I'd be happy to accept a pull request if you need it.

**Comment by alihassan360** [comment] 2018-12-18 13:33
but is there a way to disable the filtering function all together though ?
here is my current situation .. I am currently using the autocomplete asynchronously  where the suggestions are updated based on a http request. the problem is that the suggestions don't always contain the input value. in that case the current tag input removes such suggestions although it's actually a good suggestion. 

so if there is a way to opt out of filtering that would be great

**Comment by i-like-robots** [comment] 2019-04-14 10:25
`suggestionsFilter` option added in #153

**Closed by i-like-robots** 2019-04-14 10:25 UTC
Labels: duplicate, help wanted, question
