### ISSUE TITLE
Update peer dependency to React so it can be used with latest version

### ISSUE THREAD

**Issue by Arsenalist** [i-like-robots/react-tags#275] opened 2023-03-05 15:10 UTC
There's a peer dependency error when building with React 18>.  Is it possible to upgrade the peer dependency so that this can be used with the latest version of React?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: punchline@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0 || ^17.0.0" from react-tag-autocomplete@6.3.0
```

Currently in package.json we have this listed:

```
  "peerDependencies": {
    "prop-types": "^15.5.0",
    "react": "^16.5.0 || ^17.0.0",
    "react-dom": "^16.5.0 || ^17.0.0"
  },
  ```

**Comment by i-like-robots** [comment] 2023-03-08 09:53
Thanks for raising this issue. I recommend using the [next major version](https://github.com/i-like-robots/react-tag-autocomplete/) of the component instead - which is currently at release candidate stage - as this has been built entirely with React v18 in mind.

Closing as a dupe of #267

**Closed by i-like-robots** 2023-03-08 09:53 UTC
