### ISSUE TITLE
Bugs v.6 Suggestions list

### ISSUE THREAD

**Issue by filippofilip95** [i-like-robots/react-tags#173] opened 2019-10-02 09:43 UTC
Hi, thanks for a great plugin. 

Now we are using version: `6.0.0-beta.1` in production and we found some bugs.

1.  If I set `minQueryLength={0}` and focus the input for the first time suggestions are not shown. 
But if I write something to input then delete it and unfocus and focus back it works.
(just trying to accomplish https://github.com/i-like-robots/react-tags/issues/142)

2. I would like to show only the suggestions which are not selected. For this, my filter function is filtering `suggestions` prop. 
But when I select a suggestion (`suggestions` prop is also changed) but your suggestion list still shows old suggestion unless I change something in input.

I think these bugs are maybe related to each other. And it worked in v.5.

I made and a sandbox where you can reproduce bot oh them: 
https://codesandbox.io/embed/focused-sunset-r1oox

Thanks for your reply!! :)

**Comment by massoprod** [comment] 2019-10-02 09:58
Same issue

**Comment by i-like-robots** [comment] 2019-10-10 20:44
Thanks for the report @filippofilip95 and for checking against the previous version. I'll try and recreate this 🤞 for a simple fix.

**Comment by i-like-robots** [comment] 2019-10-12 17:31
This has been caused by my refactor to move the suggestion list options up into the top-level component. Whether or not it is better to revert this or add extra logic to accommodate it I'm not sure, so I'll have a think 🤔

**Comment by i-like-robots** [comment] 2019-10-13 12:55
These issues have been fixed in #177 and released in `v6.0.0-beta.2`

**Closed by i-like-robots** 2019-10-13 12:55 UTC
Labels: bug
