### ISSUE TITLE
Custom Suggestion Item?

### ISSUE THREAD

**Issue by yrik** [i-like-robots/react-tags#201] opened 2020-04-20 15:58 UTC
I have a dataset with images. I can already show an image in the input field using a custom Tag component. However, it's not possible to specify a custom suggestion item. So the user can select an item with image preview.

**Comment by i-like-robots** [comment] 2020-04-20 21:12
Closing as a duplicate of #134 - this feature is available in the [v6 beta](https://github.com/i-like-robots/react-tags/tree/6.0)

**Closed by i-like-robots** 2020-04-20 21:12 UTC
Labels: duplicate
